import {useMemo,useState} from 'react';
import {useQuery,useQueryClient} from '@tanstack/react-query';
import {AlertTriangle,CheckSquare,Clock3,UserCheck} from 'lucide-react';
import {Link} from 'react-router-dom';
import {toast} from 'sonner';
import {PageTitle,Stat,statusColor} from './Common';
import {api} from '../lib/api';
import type {Complaint,DuplicateCluster} from '../types';

type Officer={id:string;full_name:string;email:string;department?:string};

function DuplicateClusters(){
  const {data:clusters=[]}=useQuery({queryKey:['duplicate-clusters'],queryFn:()=>api<DuplicateCluster[]>('/api/admin/duplicate-clusters')});
  if(!clusters.length)return null;
  return <div className="card mt-7"><h2 className="font-display text-xl font-bold">Duplicate clusters</h2><p className="mt-1 text-sm text-slate-500">Merged reports, community reach and primary complaint ownership.</p><div className="mt-4 grid gap-3 lg:grid-cols-2">{clusters.map(cluster=><Link to={`/complaints/${cluster.primary.id}`} key={cluster.id} className="rounded-xl border border-slate-200 p-4 transition hover:border-blue-400 dark:border-slate-700"><div className="flex items-start justify-between gap-3"><div><span className="badge bg-blue-50 text-civic">{cluster.category}</span><h3 className="mt-2 font-bold">{cluster.primary.title}</h3><p className="text-xs text-slate-400">{cluster.primary.reference_number} · {cluster.primary.locality||cluster.primary.ward}</p></div><div className="text-right"><b className="text-2xl text-civic">{cluster.member_count}</b><p className="text-xs text-slate-400">reports</p></div></div><p className="mt-3 text-sm">{cluster.total_support_count} total supporters · {cluster.members.length-1} merged duplicates</p></Link>)}</div></div>;
}

export default function AuthorityOperations(){
  const qc=useQueryClient();const [overdue,setOverdue]=useState(false);const [mine,setMine]=useState(false);const [selected,setSelected]=useState<string[]>([]);const [department,setDepartment]=useState('Roads Department');const [officer,setOfficer]=useState('');
  const {data:items=[]}=useQuery({queryKey:['authority-queue',overdue,mine],queryFn:()=>api<Complaint[]>(`/api/admin/queue?overdue=${overdue}&assigned_to_me=${mine}`)});
  const {data:officers=[]}=useQuery({queryKey:['officers'],queryFn:()=>api<Officer[]>('/api/admin/officers')});
  const stats=useMemo(()=>({open:items.filter(x=>!['resolved','rejected','duplicate'].includes(x.status)).length,overdue:items.filter(x=>x.is_overdue).length,resolved:items.filter(x=>x.status==='resolved').length}),[items]);
  function toggle(id:string){setSelected(x=>x.includes(id)?x.filter(v=>v!==id):[...x,id])}
  async function bulkAssign(){if(!selected.length)return toast.error('Select at least one complaint');try{await api('/api/admin/complaints/bulk/assign',{method:'POST',body:JSON.stringify({complaint_ids:selected,assigned_to_id:officer||null,department})});toast.success(`${selected.length} complaints assigned`);setSelected([]);qc.invalidateQueries()}catch(e){toast.error((e as Error).message)}}
  async function bulkStatus(status:string){if(!selected.length)return toast.error('Select at least one complaint');try{const r=await api<{updated:string[];skipped:string[]}>('/api/admin/complaints/bulk/status',{method:'POST',body:JSON.stringify({complaint_ids:selected,status,note:`Bulk authority update: ${status.replace('_',' ')}`})});toast.success(`${r.updated.length} updated${r.skipped.length?`, ${r.skipped.length} skipped`:''}`);setSelected([]);qc.invalidateQueries()}catch(e){toast.error((e as Error).message)}}
  return <div className="section py-10"><PageTitle eyebrow="AUTHORITY OPERATIONS" title="Civic command centre" desc="Prioritise SLA risk, assign field ownership, and move verified cases through a controlled workflow."/><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><Stat label="Queue" value={items.length}/><Stat label="Active" value={stats.open}/><Stat label="Overdue SLA" value={stats.overdue}/><Stat label="Resolved" value={stats.resolved} icon="check"/></div><div className="card mt-7"><div className="flex flex-wrap items-end gap-3"><button className={overdue?'btn-primary':'btn-secondary'} onClick={()=>setOverdue(!overdue)}><AlertTriangle size={17}/>Overdue only</button><button className={mine?'btn-primary':'btn-secondary'} onClick={()=>setMine(!mine)}><UserCheck size={17}/>Assigned to me</button><label className="min-w-52 flex-1"><span className="label">Department</span><input className="input py-2" value={department} onChange={e=>setDepartment(e.target.value)}/></label><label className="min-w-52 flex-1"><span className="label">Officer</span><select className="input py-2" value={officer} onChange={e=>setOfficer(e.target.value)}><option value="">Department queue</option>{officers.map(x=><option key={x.id} value={x.id}>{x.full_name}</option>)}</select></label><button className="btn-primary" onClick={bulkAssign}><CheckSquare size={17}/>Assign selected</button><button className="btn-secondary" onClick={()=>bulkStatus('verified')}>Verify</button><button className="btn-secondary" onClick={()=>bulkStatus('in_progress')}>Start work</button></div></div><DuplicateClusters/><div className="card mt-7 overflow-x-auto"><table className="w-full min-w-[900px] text-left text-sm"><thead className="border-b text-xs uppercase text-slate-400"><tr><th className="py-3">Select</th><th>Case</th><th>Department</th><th>Severity</th><th>Status</th><th>SLA</th><th>Support</th></tr></thead><tbody>{items.map(c=><tr key={c.id} className={`border-b border-slate-100 dark:border-slate-800 ${c.is_overdue?'bg-red-50/50 dark:bg-red-950/20':''}`}><td className="py-4"><input type="checkbox" checked={selected.includes(c.id)} onChange={()=>toggle(c.id)}/></td><td><Link className="font-bold hover:text-civic" to={`/complaints/${c.id}`}>{c.title}</Link><p className="text-xs text-slate-400">{c.reference_number} · {c.ward||c.locality}</p></td><td>{c.department}</td><td className="capitalize">{c.severity}</td><td><span className={`badge ${statusColor(c.status)}`}>{c.status.replace('_',' ')}</span></td><td>{c.sla_due_at?<span className={`flex items-center gap-1 ${c.is_overdue?'font-bold text-red-600':''}`}><Clock3 size={14}/>{new Date(c.sla_due_at).toLocaleString()}</span>:'Not assigned'}</td><td>{c.support_count}</td></tr>)}</tbody></table>{!items.length&&<p className="py-12 text-center text-slate-400">No cases match this queue filter.</p>}</div></div>;
}
