import {useState} from 'react';
import {BarChart3,LogOut,Map,Menu,Moon,PlusCircle,ShieldCheck,Sun,UserRound,X} from 'lucide-react';
import {Link,NavLink,useNavigate} from 'react-router-dom';
import type {User} from '../types';
import {clearSession} from '../lib/api';
import NotificationCenter from './NotificationCenter';

const links=[['/map','Issue map',Map],['/analytics','Civic insights',BarChart3]] as const;
export default function Layout({children,user,setUser}:{children:React.ReactNode;user:User|null;setUser:(u:User|null)=>void}){
  const [open,setOpen]=useState(false);const [dark,setDark]=useState(false);const nav=useNavigate();
  function logout(){clearSession();setUser(null);nav('/')}
  function theme(){document.documentElement.classList.toggle('dark');setDark(!dark)}
  return <><header className="sticky top-0 z-[1000] border-b border-slate-200/80 bg-white/95 backdrop-blur dark:border-slate-800 dark:bg-navy/95"><div className="section flex h-16 items-center justify-between"><Link to="/" className="flex items-center gap-2 font-display text-xl font-extrabold"><span className="grid h-9 w-9 place-items-center rounded-xl bg-civic text-white"><ShieldCheck size={21}/></span>Civic<span className="text-civic">Lens</span></Link><nav className="hidden items-center gap-1 md:flex">{links.map(([to,label,I])=><NavLink key={to} to={to} className={({isActive})=>`btn px-3 ${isActive?'bg-blue-50 text-civic':'text-slate-600 dark:text-slate-300'}`}><I size={17}/>{label}</NavLink>)}{user&&<NavLink to={user.role==='admin'?'/admin':'/dashboard'} className="btn px-3"><UserRound size={17}/>Dashboard</NavLink>}</nav><div className="hidden items-center gap-2 md:flex"><button aria-label="Toggle theme" className="btn-secondary p-2.5" onClick={theme}>{dark?<Sun size={18}/>:<Moon size={18}/>}</button>{user&&<NotificationCenter/>}{user?<><Link to="/report" className="btn-primary"><PlusCircle size={18}/>Report issue</Link><button aria-label="Log out" className="btn-secondary p-2.5" onClick={logout}><LogOut size={18}/></button></>:<><Link to="/login" className="btn-secondary">Log in</Link><Link to="/register" className="btn-primary">Get started</Link></>}</div><button aria-label="Toggle navigation" className="md:hidden" onClick={()=>setOpen(!open)}>{open?<X/>:<Menu/>}</button></div>{open&&<div className="section space-y-2 pb-4 md:hidden">{links.map(([to,label])=><Link key={to} className="block py-2" to={to} onClick={()=>setOpen(false)}>{label}</Link>)}{user&&<Link className="block py-2" to={user.role==='admin'?'/admin':'/dashboard'} onClick={()=>setOpen(false)}>Dashboard</Link>}<Link className="btn-primary w-full" to={user?'/report':'/login'}>{user?'Report issue':'Log in'}</Link></div>}</header><main className="min-h-[calc(100vh-64px)]">{children}</main><footer className="border-t border-slate-200 bg-white py-10 dark:border-slate-800 dark:bg-navy"><div className="section flex flex-col justify-between gap-4 text-sm text-slate-500 sm:flex-row"><p>© 2026 CivicLens. Better streets begin with a clear report.</p><p>Built for citizens · Demo data clearly labelled</p></div></footer></>;
}
