"""initial schema

Revision ID: 0001
"""
from alembic import op
import sqlalchemy as sa

revision="0001";down_revision=None;branch_labels=None;depends_on=None
role=sa.Enum("citizen","admin",name="role");severity=sa.Enum("low","medium","high","critical",name="severity");status=sa.Enum("submitted","verified","assigned","in_progress","resolved","rejected","duplicate",name="status")

def upgrade():
    op.create_table("users",sa.Column("id",sa.String(36),primary_key=True),sa.Column("full_name",sa.String(120),nullable=False),sa.Column("email",sa.String(255),nullable=False),sa.Column("password_hash",sa.String(255),nullable=False),sa.Column("role",role,nullable=False),sa.Column("phone",sa.String(30)),sa.Column("locality",sa.String(100)),sa.Column("ward",sa.String(50)),sa.Column("is_active",sa.Boolean(),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.Column("updated_at",sa.DateTime(timezone=True),nullable=False));op.create_index("ix_users_email","users",["email"],unique=True)
    op.create_table("complaints",sa.Column("id",sa.String(36),primary_key=True),sa.Column("reference_number",sa.String(30),nullable=False),sa.Column("reporter_id",sa.String(36),sa.ForeignKey("users.id"),nullable=False),sa.Column("title",sa.String(180),nullable=False),sa.Column("description",sa.Text(),nullable=False),sa.Column("category",sa.String(60),nullable=False),sa.Column("severity",severity,nullable=False),sa.Column("status",status,nullable=False),sa.Column("confidence_score",sa.Float()),sa.Column("department",sa.String(120)),sa.Column("image_url",sa.String(500)),sa.Column("image_public_id",sa.String(200)),sa.Column("latitude",sa.Float(),nullable=False),sa.Column("longitude",sa.Float(),nullable=False),sa.Column("address",sa.String(300)),sa.Column("locality",sa.String(100)),sa.Column("ward",sa.String(50)),sa.Column("postal_code",sa.String(20)),sa.Column("complaint_letter",sa.Text()),sa.Column("support_count",sa.Integer(),nullable=False),sa.Column("duplicate_of_id",sa.String(36),sa.ForeignKey("complaints.id")),sa.Column("assigned_to_id",sa.String(36),sa.ForeignKey("users.id")),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.Column("updated_at",sa.DateTime(timezone=True),nullable=False),sa.Column("resolved_at",sa.DateTime(timezone=True)));op.create_index("ix_complaints_reference_number","complaints",["reference_number"],unique=True)
    for name in ["reporter_id","category","severity","status","latitude","longitude","created_at"]:op.create_index(f"ix_complaints_{name}","complaints",[name])
    op.create_index("ix_complaint_geo","complaints",["latitude","longitude"])
    op.create_table("complaint_status_events",sa.Column("id",sa.String(36),primary_key=True),sa.Column("complaint_id",sa.String(36),sa.ForeignKey("complaints.id"),nullable=False),sa.Column("previous_status",status),sa.Column("new_status",status,nullable=False),sa.Column("note",sa.Text()),sa.Column("changed_by_id",sa.String(36),sa.ForeignKey("users.id"),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False));op.create_index("ix_complaint_status_events_complaint_id","complaint_status_events",["complaint_id"])
    op.create_table("complaint_supports",sa.Column("id",sa.String(36),primary_key=True),sa.Column("complaint_id",sa.String(36),sa.ForeignKey("complaints.id",ondelete="CASCADE"),nullable=False),sa.Column("user_id",sa.String(36),sa.ForeignKey("users.id"),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.UniqueConstraint("complaint_id","user_id",name="uq_complaint_support"))
    op.create_table("comments",sa.Column("id",sa.String(36),primary_key=True),sa.Column("complaint_id",sa.String(36),sa.ForeignKey("complaints.id",ondelete="CASCADE"),nullable=False),sa.Column("user_id",sa.String(36),sa.ForeignKey("users.id"),nullable=False),sa.Column("content",sa.Text(),nullable=False),sa.Column("is_official",sa.Boolean(),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.Column("updated_at",sa.DateTime(timezone=True),nullable=False));op.create_index("ix_comments_complaint_id","comments",["complaint_id"])
    op.create_table("notifications",sa.Column("id",sa.String(36),primary_key=True),sa.Column("user_id",sa.String(36),sa.ForeignKey("users.id"),nullable=False),sa.Column("title",sa.String(160),nullable=False),sa.Column("message",sa.Text(),nullable=False),sa.Column("is_read",sa.Boolean(),nullable=False),sa.Column("complaint_id",sa.String(36),sa.ForeignKey("complaints.id")),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False));op.create_index("ix_notifications_user_id","notifications",["user_id"])

def downgrade():
    for table in ["notifications","comments","complaint_supports","complaint_status_events","complaints","users"]:op.drop_table(table)
