import {useEffect,useMemo,useState} from 'react';
import {useQuery} from '@tanstack/react-query';
import {Bar,BarChart,CartesianGrid,Cell,Legend,Line,LineChart,Pie,PieChart,ResponsiveContainer,Scatter,ScatterChart,Tooltip,XAxis,YAxis,ZAxis} from 'recharts';
import {Download,Filter} from 'lucide-react';
import {PageTitle,Stat} from '../components/Common';
import {api} from '../lib/api';
import type {Analytics as AnalyticsData,User} from '../types';

const colors=['#1769E0','#159A78','#E7A33E','#D94A4A','#7C6FE8'];
const hours=(value:number|null)=>value===null?'Not available':value<48?`${value} hrs`:`${(value/24).toFixed(1)} days`;

export default function Analytics(){
  const [filters,setFilters]=useState({start_date:'',end_date:'',locality:''});
  const [applied,setApplied]=useState(filters);
  const [isAdmin,setIsAdmin]=useState(false);
  useEffect(()=>{if(localStorage.getItem('token'))api<User>('/api/auth/me').then(user=>setIsAdmin(user.role==='admin')).catch(()=>undefined)},[]);
  const query=useMemo(()=>{const params=new URLSearchParams();Object.entries(applied).forEach(([key,value])=>{if(value)params.set(key,value)});return params.toString()},[applied]);
  const endpoint=isAdmin?'/api/admin/analytics':'/api/public/analytics';
  const {data:a,isLoading}=useQuery({queryKey:['analytics',endpoint,query],queryFn:()=>api<AnalyticsData>(`${endpoint}${query?`?${query}`:''}`)});
  function download(format:'csv'|'pdf'){const params=new URLSearchParams(query);params.set('format',format);const base=import.meta.env.VITE_API_BASE_URL||'http://localhost:8000';const token=localStorage.getItem('token');fetch(`${base}/api/admin/analytics/export?${params}`,{headers:token?{Authorization:`Bearer ${token}`}:{}}).then(async response=>{if(!response.ok)throw new Error('Export failed');const blob=await response.blob();const url=URL.createObjectURL(blob);const link=document.createElement('a');link.href=url;link.download=`civiclens-analytics.${format}`;link.click();URL.revokeObjectURL(url)}).catch(()=>undefined)}
  if(isLoading||!a)return <div className="section py-20">Loading civic insights…</div>;
  const categories=Object.entries(a.by_category).map(([name,value])=>({name,value}));
  const hotspots=a.hotspots.map(item=>({x:item.longitude,y:item.latitude,z:item.reports,name:item.locality}));
  return <div className="section py-10">
    <div className="mb-6 inline-flex badge bg-amber-100 text-amber-800">Demo Data · For product demonstration</div>
    <PageTitle eyebrow={isAdmin?'PRIVATE AUTHORITY ANALYTICS':'PUBLIC INSIGHTS'} title="Chennai civic health at a glance" desc="Transparent trends help communities and authorities focus attention where it matters most."/>
    <form className="card mb-7 grid items-end gap-4 md:grid-cols-4" onSubmit={event=>{event.preventDefault();setApplied(filters)}}><label><span className="label">From date</span><input className="input" type="date" value={filters.start_date} onChange={e=>setFilters({...filters,start_date:e.target.value})}/></label><label><span className="label">To date</span><input className="input" type="date" value={filters.end_date} onChange={e=>setFilters({...filters,end_date:e.target.value})}/></label><label><span className="label">Locality</span><input className="input" placeholder="e.g. Adyar" value={filters.locality} onChange={e=>setFilters({...filters,locality:e.target.value})}/></label><button className="btn-primary"><Filter size={17}/>Apply filters</button></form>
    {isAdmin&&<div className="mb-7 flex gap-3"><button className="btn-secondary" onClick={()=>download('csv')}><Download size={17}/>Download CSV</button><button className="btn-secondary" onClick={()=>download('pdf')}><Download size={17}/>Download PDF</button></div>}
    <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-5"><Stat label="Civic health score" value={`${a.civic_health_score}/100`}/><Stat label="Resolution rate" value={`${a.resolution_rate}%`} icon="check"/><Stat label="SLA compliance" value={`${a.sla_compliance_rate}%`}/><Stat label="Reopened rate" value={`${a.reopened_rate}%`}/><Stat label="Citizen satisfaction" value={`${a.citizen_satisfaction_score}/100`}/></div>
    <div className="mt-4 grid gap-4 md:grid-cols-4"><Stat label="Total reports" value={a.total}/><Stat label="Open issues" value={a.open}/><Stat label="Avg. first response" value={hours(a.avg_first_response_hours)}/><Stat label="Avg. resolution" value={hours(a.avg_resolution_hours)}/></div>
    <div className="mt-7 grid gap-7 lg:grid-cols-2"><Chart title="Monthly report and resolution trends"><ResponsiveContainer width="100%" height="88%"><LineChart data={a.monthly_trends}><CartesianGrid strokeDasharray="3 3"/><XAxis dataKey="month"/><YAxis allowDecimals={false}/><Tooltip/><Legend/><Line type="monotone" dataKey="reported" stroke="#1769E0" strokeWidth={3}/><Line type="monotone" dataKey="resolved" stroke="#159A78" strokeWidth={3}/></LineChart></ResponsiveContainer></Chart><Chart title="Top issue categories"><ResponsiveContainer width="100%" height="88%"><PieChart><Pie data={categories} dataKey="value" nameKey="name" innerRadius={65} outerRadius={105} paddingAngle={3}>{categories.map((_,i)=><Cell key={i} fill={colors[i%colors.length]}/>)}</Pie><Tooltip/></PieChart></ResponsiveContainer></Chart></div>
    <div className="mt-7 grid gap-7 lg:grid-cols-2"><Chart title="Issue hotspot map"><ResponsiveContainer width="100%" height="88%"><ScatterChart><CartesianGrid/><XAxis type="number" dataKey="x" name="longitude" domain={['auto','auto']}/><YAxis type="number" dataKey="y" name="latitude" domain={['auto','auto']}/><ZAxis type="number" dataKey="z" range={[80,700]} name="reports"/><Tooltip cursor={{strokeDasharray:'3 3'}}/><Scatter data={hotspots} fill="#D94A4A"/></ScatterChart></ResponsiveContainer></Chart><Chart title="Ward-wise civic health"><ResponsiveContainer width="100%" height="88%"><BarChart data={a.ward_health.slice(0,12)} layout="vertical"><CartesianGrid strokeDasharray="3 3"/><XAxis type="number" domain={[0,100]}/><YAxis type="category" dataKey="ward" width={80}/><Tooltip/><Bar dataKey="health_score" fill="#1769E0" radius={[0,5,5,0]}/></BarChart></ResponsiveContainer></Chart></div>
    <div className="card mt-7"><h2 className="font-display text-xl font-bold">Next-month category forecast</h2><p className="mt-1 text-sm text-slate-500">Simple monthly run-rate projection; use as a planning signal, not a guaranteed prediction.</p><div className="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{a.category_forecast.map(item=><div key={item.category} className="rounded-xl bg-slate-50 p-4 dark:bg-slate-800"><p className="text-sm text-slate-500">{item.category}</p><p className="mt-1 font-display text-2xl font-bold">{item.forecast}</p><p className="text-xs text-slate-400">forecast reports</p></div>)}</div></div>
    {isAdmin&&a.department_performance&&<div className="card mt-7"><h2 className="font-display text-xl font-bold">Department performance</h2><div className="mt-5 overflow-x-auto"><table className="w-full text-left text-sm"><thead className="border-b text-slate-500"><tr><th className="p-3">Department</th><th className="p-3">Reports</th><th className="p-3">Resolved</th><th className="p-3">Resolution rate</th><th className="p-3">Overdue</th></tr></thead><tbody>{a.department_performance.map(row=><tr key={row.department} className="border-b border-slate-100"><th className="p-3">{row.department}</th><td className="p-3">{row.total}</td><td className="p-3">{row.resolved}</td><td className="p-3">{row.resolution_rate}%</td><td className="p-3">{row.overdue}</td></tr>)}</tbody></table></div></div>}
  </div>;
}

function Chart({title,children}:{title:string;children:React.ReactNode}){return <div className="card h-96"><h2 className="font-display text-xl font-bold">{title}</h2>{children}</div>}
