import {useEffect,useState} from 'react';
import {useNavigate} from 'react-router-dom';
import {toast} from 'sonner';
import type {User} from '../types';
import {PageTitle} from '../components/Common';
import {api,clearSession} from '../lib/api';

type Preferences={email_enabled:boolean;push_enabled:boolean;whatsapp_enabled:boolean;status_alerts:boolean;nearby_critical_alerts:boolean;ward_digest:boolean;vapid_public_key?:string};
const defaults:Preferences={email_enabled:true,push_enabled:false,whatsapp_enabled:false,status_alerts:true,nearby_critical_alerts:true,ward_digest:false};
function keyBytes(value:string){const padded=value+'='.repeat((4-value.length%4)%4);const raw=atob(padded.replace(/-/g,'+').replace(/_/g,'/'));return Uint8Array.from([...raw].map(x=>x.charCodeAt(0)))}
export default function Profile({user,setUser}:{user:User;setUser:(u:null)=>void}){
  const nav=useNavigate();const [prefs,setPrefs]=useState<Preferences>(defaults);const [saving,setSaving]=useState(false);
  useEffect(()=>{api<Preferences>('/api/notification-preferences').then(setPrefs).catch(e=>toast.error(e.message))},[]);
  function toggle(key:keyof Preferences){setPrefs(value=>({...value,[key]:!value[key]}))}
  async function save(){setSaving(true);try{const body={...prefs};delete body.vapid_public_key;await api('/api/notification-preferences',{method:'PUT',body:JSON.stringify(body)});toast.success('Notification preferences saved')}catch(e){toast.error((e as Error).message)}finally{setSaving(false)}}
  async function enablePush(){try{if(!prefs.vapid_public_key)throw new Error('Browser push is not configured by the administrator');if(!('serviceWorker'in navigator)||!('PushManager'in window))throw new Error('Browser push is not supported');const permission=await Notification.requestPermission();if(permission!=='granted')throw new Error('Notification permission was not granted');const worker=await navigator.serviceWorker.ready;const subscription=await worker.pushManager.subscribe({userVisibleOnly:true,applicationServerKey:keyBytes(prefs.vapid_public_key)});const json=subscription.toJSON();await api('/api/push-subscriptions',{method:'POST',body:JSON.stringify({endpoint:subscription.endpoint,p256dh:json.keys?.p256dh,auth:json.keys?.auth})});setPrefs(x=>({...x,push_enabled:true}));toast.success('Browser push enabled')}catch(e){toast.error((e as Error).message)}}
  const option=(key:keyof Preferences,title:string,description:string)=><label className="flex items-center gap-3 rounded-xl bg-mist p-4 dark:bg-slate-800"><input type="checkbox" checked={!!prefs[key]} onChange={()=>toggle(key)}/><span><b>{title}</b><small className="block text-slate-500">{description}</small></span></label>;
  return <div className="section py-10"><PageTitle eyebrow="SETTINGS" title="Your CivicLens profile"/><div className="card max-w-2xl space-y-5"><div className="grid gap-4 sm:grid-cols-2"><label><span className="label">Full name</span><input className="input" value={user.full_name} readOnly/></label><label><span className="label">Email address</span><input className="input" value={user.email} readOnly/></label></div><h2 className="font-display text-xl font-bold">Notification preferences</h2>{option('email_enabled','Email notifications','Receive enabled CivicLens alerts by email.')}{option('status_alerts','Status-change alerts','Get updates whenever your complaint workflow changes.')}{option('nearby_critical_alerts','Nearby critical alerts','Receive urgent alerts for your ward or locality.')}{user.role==='admin'&&option('ward_digest','Ward daily digest','Receive a daily summary for your authority ward scope.')}{option('whatsapp_enabled','WhatsApp updates','Use the verified phone number linked to your account.')}<div className="flex flex-wrap gap-3"><button className="btn-primary" disabled={saving} onClick={save}>{saving?'Saving…':'Save preferences'}</button><button className="btn-secondary" onClick={enablePush}>{prefs.push_enabled?'Push enabled':'Enable browser push'}</button></div><button className="btn-secondary text-red-600" onClick={()=>{clearSession();setUser(null);nav('/')}}>Log out of CivicLens</button></div></div>;
}
