import {useEffect,useState} from 'react';
import {Camera,ChevronLeft,ChevronRight,FileText,LocateFixed,Search,Send,Sparkles,Upload} from 'lucide-react';
import {MapContainer,Marker,TileLayer,useMapEvents} from 'react-leaflet';
import {useNavigate} from 'react-router-dom';
import {toast} from 'sonner';
import {CategoryGuidance,VoiceButton} from '../components/ReportingTools';
import {api} from '../lib/api';
import {useI18n} from '../lib/i18n';
import type {Complaint,User} from '../types';

const categories=['Pothole','Garbage accumulation','Water leakage','Sewage overflow','Broken streetlight','Damaged road','Open drain','Illegal dumping','Fallen tree','Damaged public property','Other civic issue'];
type Position=[number,number];
type ReportData={title:string;description:string;category:string;severity:string;department:string;latitude:number;longitude:number;address:string;locality?:string;ward?:string;postal_code?:string;confidence_score:number;image_url?:string;image_public_id?:string;complaint_letter:string;is_demo:boolean;is_anonymous:boolean;hide_exact_location:boolean;media:{url:string;public_id?:string;mime_type:string}[]};
function Picker({pos,setPos}:{pos:Position;setPos:(p:Position)=>void}){useMapEvents({click:e=>setPos([e.latlng.lat,e.latlng.lng])});return <Marker position={pos} draggable eventHandlers={{dragend:e=>{const p=e.target.getLatLng();setPos([p.lat,p.lng])}}}/>}

export default function Report({user}:{user:User}){
  const nav=useNavigate();const {t,lang}=useI18n();const steps=[t('photo'),t('analysis'),t('details'),t('location'),t('similar'),t('letter'),t('submit')];
  const [step,setStep]=useState(0);const [files,setFiles]=useState<File[]>([]);const [previews,setPreviews]=useState<string[]>([]);const [busy,setBusy]=useState(false);const [online,setOnline]=useState(navigator.onLine);
  const [similar,setSimilar]=useState<(Complaint&{similarity_score:number;distance_m:number})[]>([]);
  const [data,setData]=useState<ReportData>({title:'',description:'',category:'Pothole',severity:'medium',department:'Roads Department',latitude:13.0827,longitude:80.2707,address:'Chennai, Tamil Nadu',confidence_score:.86,complaint_letter:'',is_demo:true,is_anonymous:false,hide_exact_location:false,media:[]});
  useEffect(()=>{const on=()=>setOnline(true),off=()=>setOnline(false);addEventListener('online',on);addEventListener('offline',off);return()=>{removeEventListener('online',on);removeEventListener('offline',off)}},[]);
  function update(values:Partial<ReportData>){setData(current=>({...current,...values}))}
  function choose(selected:File[]){if(selected.some(f=>f.size>8*1024*1024))return toast.error('Each image must be under 8 MB');setFiles(selected.slice(0,5));previews.forEach(URL.revokeObjectURL);setPreviews(selected.slice(0,5).map(URL.createObjectURL))}
  async function analyze(){const fd=new FormData();fd.append('file',files[0]);const analysis=await api<Record<string,unknown>>('/api/complaints/analyze',{method:'POST',body:fd});const media=[{url:analysis.image_url as string,public_id:analysis.image_public_id as string,mime_type:files[0].type}];if(files.length>1){const form=new FormData();files.slice(1).forEach(file=>form.append('files',file));const uploaded=await api<{items:{url:string;public_id:string;mime_type:string}[]}>('/api/complaints/media',{method:'POST',body:form});media.push(...uploaded.items)}update({...analysis,media} as Partial<ReportData>)}
  async function next(){if(step===0&&!files.length)return toast.error('Please choose at least one issue photo');if(!online)return toast.error('Your draft is safe on this screen. Reconnect to continue.');setBusy(true);try{
    if(step===0)await analyze();
    if(step===3){const location=await api<Partial<ReportData>>(`/api/location/reverse?latitude=${data.latitude}&longitude=${data.longitude}`);const located={...data,...location};setData(located);setSimilar(await api('/api/complaints/similar',{method:'POST',body:JSON.stringify(located)}))}
    if(step===4){const result=await api<{letter:string}>('/api/complaints/generate-letter',{method:'POST',body:JSON.stringify({citizen_name:user.full_name,category:data.category,description:data.description,address:data.address,severity:data.severity,department:data.department,reference_number:'Generated on submission'})});update({complaint_letter:result.letter})}
    if(step===6){const complaint=await api<Complaint>('/api/complaints',{method:'POST',body:JSON.stringify(data)});toast.success(`Submitted ${complaint.reference_number}`);return nav(`/complaints/${complaint.id}`)}
    setStep(value=>Math.min(6,value+1));
  }catch(error){toast.error((error as Error).message)}finally{setBusy(false)}}
  function locate(){navigator.geolocation?.getCurrentPosition(p=>update({latitude:p.coords.latitude,longitude:p.coords.longitude}),()=>toast.error('Location unavailable. Select on the map.'))}
  return <div className="section py-10"><div className="mx-auto max-w-4xl">
    {!online&&<div className="mb-5 rounded-xl bg-amber-100 p-3 text-sm font-bold text-amber-900">Offline mode — your current form stays on screen. Reconnect before analysis or submission.</div>}
    <p className="text-sm font-bold text-civic">{lang==='ta'?'பிரச்சினையைப் புகாரளி':'REPORT AN ISSUE'}</p><h1 className="font-display text-3xl font-extrabold">{lang==='ta'?'தெளிவான நகர்ப்புற புகாரை உருவாக்குங்கள்':'Create a clear civic report'}</h1>
    <div className="mt-7 flex gap-1">{steps.map((label,index)=><div className="flex-1" key={label}><div className={`h-1.5 rounded-full ${index<=step?'bg-civic':'bg-slate-200'}`}/><span className="mt-2 hidden text-xs text-slate-500 sm:block">{label}</span></div>)}</div>
    <div className="card mt-8 min-h-[480px] p-6 sm:p-8">
      {step===0&&<div className="grid place-items-center py-8 text-center"><span className="grid h-16 w-16 place-items-center rounded-2xl bg-blue-50 text-civic"><Camera size={30}/></span><h2 className="mt-5 font-display text-2xl font-bold">Add up to five photos</h2><p className="mt-2 text-slate-500">Show the issue from different safe angles. JPEG, PNG or WebP; 8 MB each.</p><label className="mt-7 cursor-pointer rounded-2xl border-2 border-dashed border-blue-200 p-8 hover:bg-blue-50"><Upload className="mx-auto text-civic"/><span className="mt-2 block font-bold">{files.length?`${files.length} photo${files.length>1?'s':''} selected`:'Choose or capture photos'}</span><input hidden multiple type="file" accept="image/jpeg,image/png,image/webp" onChange={e=>choose(Array.from(e.target.files||[]))}/></label>{previews.length>0&&<div className="mt-6 grid w-full grid-cols-2 gap-3 sm:grid-cols-3">{previews.map(src=><img key={src} className="h-32 w-full rounded-xl object-cover" src={src}/>)}</div>}</div>}
      {step===1&&<div><div className="flex items-center gap-3"><Sparkles className="text-civic"/><h2 className="font-display text-2xl font-bold">{data.is_demo?'Demo AI analysis':'AI analysis'}</h2></div><p className="mt-2 text-slate-500">AI suggestions are never final. Review and edit every field.</p><div className="mt-7 grid gap-4 sm:grid-cols-2">{[['Category',data.category],['Severity',data.severity],['Confidence',`${Math.round(data.confidence_score*100)}%`],['Department',data.department]].map(([label,value])=><div key={label} className="rounded-xl bg-mist p-4 dark:bg-slate-800"><p className="text-xs font-bold uppercase text-slate-400">{label}</p><p className="mt-1 font-bold capitalize">{value}</p></div>)}</div>{data.confidence_score<.7&&<div className="mt-5 rounded-xl bg-amber-50 p-4 font-semibold text-amber-900">Low-confidence result. Please check the category and description carefully.</div>}<h3 className="mt-6 font-bold">{data.title}</h3><p className="mt-2 text-slate-500">{data.description}</p></div>}
      {step===2&&<div className="space-y-4"><h2 className="font-display text-2xl font-bold">Confirm issue details</h2><label><span className="label">Title</span><input className="input" value={data.title} onChange={e=>update({title:e.target.value})}/></label><label><span className="label">Description</span><textarea className="input min-h-32" value={data.description} onChange={e=>update({description:e.target.value})}/></label><VoiceButton onText={text=>update({description:`${data.description} ${text}`.trim()})}/><div className="grid gap-4 sm:grid-cols-2"><label><span className="label">Category</span><select className="input" value={data.category} onChange={e=>update({category:e.target.value})}>{categories.map(x=><option key={x}>{x}</option>)}</select></label><label><span className="label">Severity</span><select className="input" value={data.severity} onChange={e=>update({severity:e.target.value})}>{['low','medium','high','critical'].map(x=><option key={x}>{x}</option>)}</select></label></div><CategoryGuidance category={data.category}/></div>}
      {step===3&&<div><div className="flex justify-between gap-3"><div><h2 className="font-display text-2xl font-bold">Pin the location</h2><p className="text-slate-500">Click the map or drag the pin.</p></div><button className="btn-secondary" onClick={locate}><LocateFixed size={18}/>Use my location</button></div><div className="mt-5 h-72 overflow-hidden rounded-2xl"><MapContainer center={[data.latitude,data.longitude]} zoom={15} key={`${data.latitude}-${data.longitude}`}><TileLayer attribution="&copy; OpenStreetMap" url="https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png"/><Picker pos={[data.latitude,data.longitude]} setPos={p=>update({latitude:p[0],longitude:p[1]})}/></MapContainer></div><input className="input mt-4" value={data.address} onChange={e=>update({address:e.target.value})} placeholder="Address or landmark"/><label className="mt-3 flex items-center gap-3 rounded-xl bg-mist p-4 dark:bg-slate-800"><input type="checkbox" checked={data.hide_exact_location} onChange={e=>update({hide_exact_location:e.target.checked})}/><span><b>Hide exact public location</b><small className="block text-slate-500">Public maps show an approximate pin; authorities retain the submitted location.</small></span></label></div>}
      {step===4&&<div><Search className="text-civic"/><h2 className="mt-3 font-display text-2xl font-bold">Nearby similar reports</h2><p className="text-slate-500">We checked a 300 metre radius to reduce duplicates.</p><div className="mt-5 space-y-3">{similar.length?similar.map(item=><div key={item.id} className="flex items-center justify-between rounded-xl border p-4"><div><b>{item.title}</b><p className="text-sm text-slate-500">{item.distance_m} m away · {Math.round(item.similarity_score*100)}% similar · {item.status}</p></div><button onClick={()=>api(`/api/complaints/${item.id}/support`,{method:'POST'}).then(()=>toast.success('Support added'))} className="btn-secondary">Support</button></div>):<div className="rounded-xl bg-emerald-50 p-5 text-emerald-800">No strong duplicate found nearby. Continue with a new report.</div>}</div></div>}
      {step===5&&<div><FileText className="text-civic"/><h2 className="mt-3 font-display text-2xl font-bold">Complaint letter ready</h2><p className="text-slate-500">Review and edit this professional draft.</p><textarea className="input mt-5 min-h-72 font-mono text-sm" value={data.complaint_letter} onChange={e=>update({complaint_letter:e.target.value})}/></div>}
      {step===6&&<div className="py-8 text-center"><span className="mx-auto grid h-16 w-16 place-items-center rounded-2xl bg-emerald-50 text-emerald"><Send size={30}/></span><h2 className="mt-5 font-display text-3xl font-bold">Ready to submit?</h2><p className="mx-auto mt-3 max-w-lg text-slate-500">Your report becomes public, while your private contact details stay protected.</p><label className="mx-auto mt-6 flex max-w-lg items-center gap-3 rounded-xl bg-mist p-4 text-left dark:bg-slate-800"><input type="checkbox" checked={data.is_anonymous} onChange={e=>update({is_anonymous:e.target.checked})}/><span><b>Publish anonymously</b><small className="block text-slate-500">Your identity remains visible only to authorised staff.</small></span></label><div className="mx-auto mt-4 max-w-lg rounded-xl border p-5 text-left"><b>{data.title}</b><p className="mt-1 text-sm">{data.category} · {data.severity} · {data.address}</p><p className="mt-2 text-xs text-slate-400">{data.media.length} photo(s) attached</p></div></div>}
    </div><div className="mt-5 flex justify-between"><button className="btn-secondary" disabled={step===0||busy} onClick={()=>setStep(x=>x-1)}><ChevronLeft/>Back</button><button className="btn-primary" disabled={busy||!online} onClick={next}>{busy?'Working…':step===6?'Submit complaint':'Continue'}{step===6?<Send size={18}/>:<ChevronRight/>}</button></div>
  </div></div>
}
